FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
COPY angular.json ./
COPY tsconfig*.json ./

RUN npm ci


COPY src ./src
COPY public ./public


RUN npm run build --prod

FROM nginx:alpine


COPY --from=build /app/dist/* /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/nginx.conf

# Exponer puerto
EXPOSE 80

ENV NODE_ENV=production

CMD ["nginx", "-g", "daemon off;"]